-- liquibase formatted sql

-- changeset user:1
-- Создание таблицы "books" для хранения информации о книгах
CREATE TABLE books(
    id  BIGINT generated by default as identity primary key,
    shelfNumber INT,
    title TEXT,
    author TEXT,
    publicationDate DATE
);
